import type { Product } from "@/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Black Dog Triple Gold Reserve",
    slug: "black-dog-triple-gold-reserve",
    description: "Premium scotch whisky with a rich, rounded flavor.",
    category: "whisky",
    brand: "Black Dog",
    price: 2660,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/black-dog.jpg"],
    stock: 50,
    featured: true,
    rating: 4.5,
    reviewCount: 120,
    tags: ["whisky", "scotch", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Johnnie Walker Black Label",
    slug: "johnnie-walker-black-label",
    description: "Iconic blend with depth and complexity.",
    category: "whisky",
    brand: "Johnnie Walker",
    price: 3750,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/johnnie.jpg"],
    stock: 60,
    featured: true,
    rating: 4.8,
    reviewCount: 350,
    tags: ["whisky", "scotch", "blended"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Johnnie Walker Red Label",
    slug: "johnnie-walker-red-label",
    description: "Pioneer blend, versatile and vibrant.",
    category: "whisky",
    brand: "Johnnie Walker",
    price: 1980,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/johnnie-red.webp"],
    stock: 80,
    featured: false,
    rating: 4.3,
    reviewCount: 200,
    tags: ["whisky", "scotch", "blended"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Johnnie Walker Double Black",
    slug: "johnnie-walker-double-black",
    description: "Intense deep character with smoky finish.",
    category: "whisky",
    brand: "Johnnie Walker",
    price: 4750,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/johnnie.jpg"],
    stock: 30,
    featured: true,
    rating: 4.7,
    reviewCount: 150,
    tags: ["whisky", "scotch", "smoky"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "Chivas Regal 12 Year",
    slug: "chivas-regal-12",
    description: "Smooth and generous blend of fine malt and grain whiskies.",
    category: "whisky",
    brand: "Chivas Regal",
    price: 3440,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/chivas.webp"],
    stock: 55,
    featured: true,
    rating: 4.6,
    reviewCount: 220,
    tags: ["whisky", "scotch", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "Dewar's White Label",
    slug: "dewars-white-label",
    description: "Double aged for extra smoothness.",
    category: "whisky",
    brand: "Dewar's",
    price: 2000,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/dewars.jpg"],
    stock: 65,
    featured: false,
    rating: 4.4,
    reviewCount: 180,
    tags: ["whisky", "scotch", "blended"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    name: "Paul John Brilliance",
    slug: "paul-john-brilliance",
    description: "Indian single malt with unpeated brilliance.",
    category: "whisky",
    brand: "Paul John",
    price: 2570,
    alcoholPercentage: 46,
    volume: "750ml",
    origin: "Goa, India",
    images: ["/bottels/paul.jpg.webp"],
    stock: 25,
    featured: true,
    rating: 4.7,
    reviewCount: 90,
    tags: ["whisky", "indian", "single malt"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "Kingfisher Premium Bottle",
    slug: "kingfisher-premium-bottle",
    description: "The King of Good Times. Classic lager.",
    category: "beer",
    brand: "Kingfisher",
    price: 180,
    alcoholPercentage: 4.8,
    volume: "650ml",
    origin: "India",
    images: ["/bottels/kingfisher.jpg"],
    stock: 200,
    featured: true,
    rating: 4.5,
    reviewCount: 500,
    tags: ["beer", "lager", "indian"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    name: "Kingfisher Premium Can",
    slug: "kingfisher-premium-can",
    description: "The King of Good Times in a convenient can.",
    category: "beer",
    brand: "Kingfisher",
    price: 140,
    alcoholPercentage: 4.8,
    volume: "500ml",
    origin: "India",
    images: ["/bottels/kingfisher-can.jpg"],
    stock: 300,
    featured: false,
    rating: 4.5,
    reviewCount: 450,
    tags: ["beer", "lager", "can"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    name: "Elephant Strong Beer Bottle",
    slug: "elephant-strong-beer-bottle",
    description: "Strong and robust beer.",
    category: "beer",
    brand: "Elephant",
    price: 250,
    alcoholPercentage: 7,
    volume: "650ml",
    origin: "India",
    images: ["/bottels/elephant-beer.webp"],
    stock: 150,
    featured: false,
    rating: 4.2,
    reviewCount: 150,
    tags: ["beer", "strong", "bottle"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    name: "Elephant Strong Beer Can",
    slug: "elephant-strong-beer-can",
    description: "Strong beer in a can.",
    category: "beer",
    brand: "Elephant",
    price: 190,
    alcoholPercentage: 7,
    volume: "500ml",
    origin: "India",
    images: ["/bottels/elephant-can.webp"],
    stock: 180,
    featured: false,
    rating: 4.2,
    reviewCount: 140,
    tags: ["beer", "strong", "can"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    name: "Kingfisher Ultra Max Bottle",
    slug: "kingfisher-ultra-max-bottle",
    description: "Maximum taste, maximum smoothness.",
    category: "beer",
    brand: "Kingfisher",
    price: 250,
    alcoholPercentage: 6,
    volume: "650ml",
    origin: "India",
    images: ["/bottels/kingfisher-ultra.jpg"],
    stock: 100,
    featured: true,
    rating: 4.6,
    reviewCount: 200,
    tags: ["beer", "strong", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "13",
    name: "Kingfisher Ultra Max Can",
    slug: "kingfisher-ultra-max-can",
    description: "Ultra Max smoothness in a can.",
    category: "beer",
    brand: "Kingfisher",
    price: 190,
    alcoholPercentage: 6,
    volume: "500ml",
    origin: "India",
    images: ["/bottels/kingfisher-ultra-max-can.webp"],
    stock: 120,
    featured: false,
    rating: 4.6,
    reviewCount: 180,
    tags: ["beer", "strong", "can"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "14",
    name: "Heineken Can",
    slug: "heineken-can",
    description: "Premium quality lager.",
    category: "beer",
    brand: "Heineken",
    price: 270,
    alcoholPercentage: 5,
    volume: "500ml",
    origin: "Netherlands",
    images: ["/bottels/heineken-lager-can.webp"],
    stock: 200,
    featured: true,
    rating: 4.5,
    reviewCount: 300,
    tags: ["beer", "lager", "can"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15",
    name: "Blenders Pride",
    slug: "blenders-pride",
    description: "Smooth blend of Indian grain spirits and scotch malts.",
    category: "whisky",
    brand: "Blenders Pride",
    price: 1040,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/blender-pride.webp"],
    stock: 300,
    featured: false,
    rating: 4.2,
    reviewCount: 600,
    tags: ["whisky", "indian", "blend"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "16",
    name: "Blenders Pride Reserve Collection",
    slug: "blenders-pride-reserve",
    description: "A premium reserve blend.",
    category: "whisky",
    brand: "Blenders Pride",
    price: 1260,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/blender-pride.webp"],
    stock: 150,
    featured: true,
    rating: 4.4,
    reviewCount: 250,
    tags: ["whisky", "indian", "reserve"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "17",
    name: "Magic Moments Vodka",
    slug: "magic-moments",
    description: "Smooth grain vodka.",
    category: "vodka",
    brand: "Magic Moments",
    price: 720,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/magic-moment-vodka.jpeg"],
    stock: 400,
    featured: false,
    rating: 4.0,
    reviewCount: 500,
    tags: ["vodka", "indian", "grain"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "18",
    name: "Grey Goose Vodka",
    slug: "grey-goose-vodka-premium",
    description: "Premium French vodka.",
    category: "vodka",
    brand: "Grey Goose",
    price: 3730,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "France",
    images: ["/bottels/grey-goose-vodka.webp"],
    stock: 40,
    featured: true,
    rating: 4.8,
    reviewCount: 150,
    tags: ["vodka", "french", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "19",
    name: "Jaisalmer Gin",
    slug: "jaisalmer-gin",
    description: "Indian craft gin with botanicals.",
    category: "gin",
    brand: "Jaisalmer",
    price: 5000,
    alcoholPercentage: 43,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/jaisalmer-gin.jpg"],
    stock: 30,
    featured: true,
    rating: 4.6,
    reviewCount: 80,
    tags: ["gin", "indian", "craft"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "20",
    name: "100 Pipers",
    slug: "100-pipers",
    description: "Smooth scotch whisky.",
    category: "whisky",
    brand: "100 Pipers",
    price: 2130,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/pipers.jpg"],
    stock: 200,
    featured: false,
    rating: 4.3,
    reviewCount: 220,
    tags: ["whisky", "scotch", "blended"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "21",
    name: "McDowell's No.1",
    slug: "mcdowells-no1",
    description: "Popular Indian whisky.",
    category: "whisky",
    brand: "McDowell's",
    price: 610,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/mc-dowells.jpg"],
    stock: 500,
    featured: false,
    rating: 3.8,
    reviewCount: 800,
    tags: ["whisky", "indian", "popular"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "22",
    name: "Imperial Blue",
    slug: "imperial-blue",
    description: "Smooth grain whisky.",
    category: "whisky",
    brand: "Imperial Blue",
    price: 500,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/imperial-blue.jpg"],
    stock: 550,
    featured: false,
    rating: 3.9,
    reviewCount: 750,
    tags: ["whisky", "indian", "popular"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "23",
    name: "Black & White",
    slug: "black-and-white",
    description: "Classic blend for sharing.",
    category: "whisky",
    brand: "Black & White",
    price: 2000,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/black-white.jpg"],
    stock: 180,
    featured: true,
    rating: 4.2,
    reviewCount: 300,
    tags: ["whisky", "scotch", "blend"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "24",
    name: "Old Monk Rum",
    slug: "old-monk",
    description: "Iconic dark rum.",
    category: "rum",
    brand: "Old Monk",
    price: 490,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/old-monk.jpg"],
    stock: 600,
    featured: true,
    rating: 4.8,
    reviewCount: 1000,
    tags: ["rum", "dark", "indian"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "25",
    name: "All Seasons",
    slug: "all-seasons",
    description: "Golden collection whisky.",
    category: "whisky",
    brand: "All Seasons",
    price: 730,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/allseasonswhisky.heic"],
    stock: 300,
    featured: false,
    rating: 4.0,
    reviewCount: 200,
    tags: ["whisky", "indian", "popular"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "26",
    name: "Bacardi Limon",
    slug: "bacardi-limon",
    description: "Citrus flavored rum.",
    category: "rum",
    brand: "Bacardi",
    price: 1100,
    alcoholPercentage: 35,
    volume: "750ml",
    origin: "Puerto Rico",
    images: ["/bottels/bacardi-limon.webp"],
    stock: 100,
    featured: true,
    rating: 4.3,
    reviewCount: 180,
    tags: ["rum", "citrus", "flavored"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "27",
    name: "Breezer",
    slug: "breezer",
    description: "Refreshing fruity alcoholic drink.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/bacardi-breezer.jpg"],
    stock: 400,
    featured: false,
    rating: 4.1,
    reviewCount: 350,
    tags: ["rtd", "fruity", "refreshing"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "28",
    name: "Budweiser Bottle",
    slug: "budweiser-bottle",
    description: "King of Beers.",
    category: "beer",
    brand: "Budweiser",
    price: 280,
    alcoholPercentage: 5,
    volume: "650ml",
    origin: "USA",
    images: ["/bottels/budweiser.png"],
    stock: 250,
    featured: true,
    rating: 4.4,
    reviewCount: 400,
    tags: ["beer", "lager", "usa"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "29",
    name: "Godfather Super Strong",
    slug: "godfather",
    description: "Legendary strong beer.",
    category: "beer",
    brand: "Godfather",
    price: 180,
    alcoholPercentage: 7.5,
    volume: "650ml",
    origin: "India",
    images: ["/bottels/godfater.jpg"],
    stock: 150,
    featured: false,
    rating: 4.1,
    reviewCount: 120,
    tags: ["beer", "strong", "indian"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "30",
    name: "J&B Rare",
    slug: "j-and-b-rare",
    description: "Balanced blend of 42 whiskies.",
    category: "whisky",
    brand: "J&B",
    price: 1980,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/JB_Rare.jpg"],
    stock: 80,
    featured: false,
    rating: 4.2,
    reviewCount: 100,
    tags: ["whisky", "scotch", "blend"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "31",
    name: "Maharani Mahansar",
    slug: "maharani-mahansar",
    description: "Heritage royal liquor from Rajasthan.",
    category: "brandy", 
    brand: "Mahansar",
    price: 500,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "Rajasthan, India",
    images: ["/bottels/maharani-mahansar.webp"],
    stock: 60,
    featured: true,
    rating: 4.5,
    reviewCount: 90,
    tags: ["heritage", "rajasthan", "royal"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "32",
    name: "Oaksmith Gold",
    slug: "oaksmith-gold",
    description: "International blended whisky.",
    category: "whisky",
    brand: "Oaksmith",
    price: 770,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/oak-smith-whisky.jpg"],
    stock: 120,
    featured: true,
    rating: 4.3,
    reviewCount: 150,
    tags: ["whisky", "blend", "international"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "33",
    name: "Jameson Irish Whiskey",
    slug: "jameson-irish-whiskey",
    description: "Triple distilled, smooth Irish whiskey.",
    category: "whisky",
    brand: "Jameson",
    price: 2430,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Ireland",
    images: ["/bottels/jameson.jpg"],
    stock: 100,
    featured: true,
    rating: 4.8,
    reviewCount: 400,
    tags: ["whisky", "irish", "smooth"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "34",
    name: "Rockford Reserve",
    slug: "rockford-reserve",
    description: "Fine blended whisky with oak finish.",
    category: "whisky",
    brand: "Rockford",
    price: 1200,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/rockford.jpg"],
    stock: 150,
    featured: true,
    rating: 4.4,
    reviewCount: 200,
    tags: ["whisky", "blend", "smooth"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "35",
    name: "Ballantine's Finest",
    slug: "ballantines-finest",
    description: "Complex, refined and elegant scotch whisky.",
    category: "whisky",
    brand: "Ballantine's",
    price: 1830,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Scotland",
    images: ["/bottels/Ballantines_Fines.jpeg"],
    stock: 120,
    featured: true,
    rating: 4.6,
    reviewCount: 300,
    tags: ["whisky", "scotch", "blend"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "36",
    name: "Antiquity Blue",
    slug: "antiquity-blue",
    description: "The true blue of whiskies.",
    category: "whisky",
    brand: "Antiquity",
    price: 1100,
    alcoholPercentage: 42.8,
    volume: "750ml",
    origin: "India",
    images: ["/bottels/antiquity.jpg"],
    stock: 100,
    featured: true,
    rating: 4.5,
    reviewCount: 180,
    tags: ["whisky", "indian", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "37",
    name: "Bacardi Breezer Blackberry",
    slug: "bacardi-breezer-blackberry",
    description: "Delicious blackberry flavored alcoholic beverage.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/bacardi-breezer-blackberry.jpg"],
    stock: 200,
    featured: false,
    rating: 4.2,
    reviewCount: 150,
    tags: ["rtd", "fruit", "blackberry"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "38",
    name: "Bacardi Breezer Cranberry",
    slug: "bacardi-breezer-cranberry",
    description: "Refreshing cranberry flavored alcoholic beverage.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/BACARDI-BREEZER-CRANBERRY.jpg"],
    stock: 200,
    featured: false,
    rating: 4.3,
    reviewCount: 160,
    tags: ["rtd", "fruit", "cranberry"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "39",
    name: "Bacardi Breezer Jamaican Passion",
    slug: "bacardi-breezer-jamaican",
    description: "Exotic Jamaican passion fruit flavor.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/BACARDI-BREEZER-JAMAICAN.jpg"],
    stock: 200,
    featured: false,
    rating: 4.4,
    reviewCount: 140,
    tags: ["rtd", "fruit", "tropical"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "40",
    name: "Bacardi Breezer Orange",
    slug: "bacardi-breezer-orange",
    description: "Zesty orange flavored alcoholic beverage.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/BACARDI-BREEZER-ORANGE.jpg"],
    stock: 200,
    featured: false,
    rating: 4.2,
    reviewCount: 130,
    tags: ["rtd", "fruit", "citrus"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "41",
    name: "Bacardi Breezer Ripe Mango",
    slug: "bacardi-breezer-ripe-mango",
    description: "Sweet ripe mango flavored alcoholic beverage.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/BACARDI-BREEZER-RIPE-MANGO-PEACH.jpg"],
    stock: 200,
    featured: false,
    rating: 4.5,
    reviewCount: 170,
    tags: ["rtd", "fruit", "mango"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "42",
    name: "Bacardi Breezer Watermelon Mint",
    slug: "bacardi-breezer-watermelon",
    description: "Cool watermelon and mint flavor.",
    category: "beer",
    brand: "Bacardi",
    price: 120,
    alcoholPercentage: 4.8,
    volume: "275ml",
    origin: "India",
    images: ["/bottels/BACARDI-BREEZER-WATERMELON-MINT.jpg"],
    stock: 200,
    featured: false,
    rating: 4.3,
    reviewCount: 145,
    tags: ["rtd", "fruit", "watermelon"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "43",
    name: "Bacardi Carta Oro",
    slug: "bacardi-carta-oro",
    description: "Golden rum with rich, toasted flavors.",
    category: "rum",
    brand: "Bacardi",
    price: 1100,
    alcoholPercentage: 40,
    volume: "750ml",
    origin: "Puerto Rico",
    images: ["/bottels/bacardi-carta-oro.jpg"],
    stock: 100,
    featured: true,
    rating: 4.6,
    reviewCount: 180,
    tags: ["rum", "gold", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]

export const MOCK_PRODUCTS = mockProducts

// Helper function to filter and sort products
export function getFilteredProducts(filters: {
  category?: string
  brand?: string
  minPrice?: number
  maxPrice?: number
  minAlcohol?: number
  maxAlcohol?: number
  rating?: number
  inStock?: boolean
  search?: string
  sortBy?: string
  page?: number
  limit?: number
}) {
  let filtered = [...mockProducts]

  // Apply filters
  if (filters.category) {
    filtered = filtered.filter((p) => p.category === filters.category)
  }

  if (filters.brand) {
    filtered = filtered.filter((p) => p.brand === filters.brand)
  }

  if (filters.minPrice !== undefined) {
    filtered = filtered.filter((p) => p.price >= filters.minPrice!)
  }

  if (filters.maxPrice !== undefined) {
    filtered = filtered.filter((p) => p.price <= filters.maxPrice!)
  }

  if (filters.minAlcohol !== undefined) {
    filtered = filtered.filter((p) => p.alcoholPercentage >= filters.minAlcohol!)
  }

  if (filters.maxAlcohol !== undefined) {
    filtered = filtered.filter((p) => p.alcoholPercentage <= filters.maxAlcohol!)
  }

  if (filters.rating !== undefined) {
    filtered = filtered.filter((p) => p.rating >= filters.rating!)
  }

  if (filters.inStock) {
    filtered = filtered.filter((p) => p.stock > 0)
  }

  if (filters.search) {
    const searchLower = filters.search.toLowerCase()
    filtered = filtered.filter(
      (p) =>
        p.name.toLowerCase().includes(searchLower) ||
        p.description.toLowerCase().includes(searchLower) ||
        p.brand.toLowerCase().includes(searchLower) ||
        p.tags.some((tag) => tag.toLowerCase().includes(searchLower)),
    )
  }

  // Apply sorting
  if (filters.sortBy) {
    switch (filters.sortBy) {
      case "price-asc":
        filtered.sort((a, b) => a.price - b.price)
        break
      case "price-desc":
        filtered.sort((a, b) => b.price - a.price)
        break
      case "name-asc":
        filtered.sort((a, b) => a.name.localeCompare(b.name))
        break
      case "name-desc":
        filtered.sort((a, b) => b.name.localeCompare(a.name))
        break
      case "rating":
        filtered.sort((a, b) => b.rating - a.rating)
        break
      case "newest":
        filtered.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
        break
    }
  }

  // Pagination
  const page = filters.page || 1
  const limit = filters.limit || 12
  const startIndex = (page - 1) * limit
  const endIndex = startIndex + limit

  const paginated = filtered.slice(startIndex, endIndex)

  return {
    products: paginated,
    total: filtered.length,
    page,
    limit,
    totalPages: Math.ceil(filtered.length / limit),
  }
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug)
}

export function getBrands(): string[] {
  return Array.from(new Set(mockProducts.map((p) => p.brand))).sort()
}
